# Problem Statement : Hospital Patient Data Analysis

In [ ]:
import pandas as pd

# 1.Loading the datasets and showing summary with info().

patient_df = pd.read_csv("Patient_Data.csv")
billing_df = pd.read_csv("Billing_Data.csv")

In [2]:
# Display structure and data types
patient_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      str
 2   Department      6 non-null      str
 3   Doctor          6 non-null      str
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      str
dtypes: float64(1), int64(2), str(4)
memory usage: 468.0 bytes

In [3]:
billing_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         5 non-null      int64
 1   InsuranceCovered  5 non-null      int64
 2   FinalAmount       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
# 2.Selecting only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
billing_columns = ['PatientID', 'Department', 'Doctor', 'BillAmount']
patient_df = patient_df[billing_columns]
patient_df

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [5]:
# 3.Droping administrative columns like ['ReceptionistID', 'CheckInTime'].
admin_cols = ['ReceptionistID', 'CheckInTime']
patient_df.drop(columns=admin_cols, inplace=True, errors='ignore' )
print(patient_df.head())

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN

In [ ]:
# 4.Finding total bill amount per department by using groupby().
department_revenue = patient_df.groupby('Department')['BillAmount'].sum()
print(department_revenue)

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [ ]:
# 5.Removing duplicate patient records based on PatientID.
patient_df.drop_duplicates(subset='PatientID', inplace=True)

billing_df.drop_duplicates(subset='PatientID',inplace=True )

In [ ]:
# 6.Filling missing BillAmount values with the mean bill amount.
mean_bill = round(patient_df['BillAmount'].mean(), 1)
bill_col_index = patient_df.columns.get_loc('BillAmount')

for i in range(len(patient_df)):
    if pd.isna(patient_df.iloc[i, bill_col_index]):
        patient_df.iloc[i, bill_col_index] = mean_bill
    patient_df.iloc[i, bill_col_index] = round(patient_df.iloc[i, bill_col_index], 1)

In [ ]:
# 7.Merging the both billing dataset + patient dataset based on PatientID.

hospital_df = pd.merge(
    patient_df,
    billing_df,
    on='PatientID',
    how='left'
)
hospital_df.head()

,PatientID,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Cardiology,Dr. Smith,5000.0,2000,3000
1,102,Neurology,Dr. John,6233.3,1500,3500
2,103,Orthopedics,Dr. Lee,7500.0,2500,5000
3,104,Cardiology,Dr. Smith,6200.0,3000,3200
4,105,Dermatology,Dr. Rose,6233.3,1000,4000

In [10]:
# 8.Concatenating an additional DataFrame that contains new patients for the current week (row-wise).
# Example new weekly patients DataFrame
new_patients_df = pd.DataFrame({
    'PatientID': [106,107],
    'Department': ['Cardiology', 'Neurology'],
    'Doctor': ['Dr. Rao', 'Dr. Mehta'],
    'BillAmount': [4500, 5200] 
})

hospital_df = pd.concat([hospital_df, new_patients_df], axis=0, ignore_index=True)
hospital_df

,PatientID,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Cardiology,Dr. Smith,5000.0,2000.0,3000.0
1,102,Neurology,Dr. John,6233.3,1500.0,3500.0
2,103,Orthopedics,Dr. Lee,7500.0,2500.0,5000.0
3,104,Cardiology,Dr. Smith,6200.0,3000.0,3200.0
4,105,Dermatology,Dr. Rose,6233.3,1000.0,4000.0
5,106,Cardiology,Dr. Rao,4500.0,NaN,NaN
6,107,Neurology,Dr. Mehta,5200.0,NaN,NaN

In [11]:
# 9.Concatenating new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).
new_billing = pd.DataFrame({
    'PatientID'        : [106, 107],
    'InsuranceCovered' : [1800, 2100],
    'FinalAmount'      : [2700, 3100]
})

hospital_df = hospital_df.set_index('PatientID')
hospital_df.update(new_billing.set_index('PatientID'))   # column‑wise fill
hospital_df.reset_index(inplace=True)

In [12]:
# 10.Final Cleaned Dataset
hospital_df

,PatientID,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Cardiology,Dr. Smith,5000.0,2000.0,3000.0
1,102,Neurology,Dr. John,6233.3,1500.0,3500.0
2,103,Orthopedics,Dr. Lee,7500.0,2500.0,5000.0
3,104,Cardiology,Dr. Smith,6200.0,3000.0,3200.0
4,105,Dermatology,Dr. Rose,6233.3,1000.0,4000.0
5,106,Cardiology,Dr. Rao,4500.0,1800.0,2700.0
6,107,Neurology,Dr. Mehta,5200.0,2100.0,3100.0

In [ ]:
# Total revenue (BillAmount) per department
dept_rev = hospital_df.groupby('Department')['BillAmount'].sum()
print("\nRevenue per department (BillAmount):")
print(dept_rev)

# Doctor‑wise average final amount received from patients
doc_perf = hospital_df.groupby('Doctor')['FinalAmount'].mean()
print("\nDoctor performance – average FinalAmount:")
print(doc_perf)

Revenue per department (BillAmount):
Department
Cardiology     15700.0
Dermatology     6233.3
Neurology      11433.3
Orthopedics     7500.0
Name: BillAmount, dtype: float64

Doctor performance – average FinalAmount:
Doctor
Dr. John     3500.0
Dr. Lee      5000.0
Dr. Mehta    3100.0
Dr. Rao      2700.0
Dr. Rose     4000.0
Dr. Smith    3100.0
Name: FinalAmount, dtype: float64