# Python Assignment: Data Structures, Functions, Numpy & Pandas

## Section A: Data Structures & Control Structures

### 1. Creating a list of five integers and printing the result of each operation: append, extend, insert, remove, pop, index, count, sort, reverse and clear.

In [1]:
numbers = [50,40,30,20,10]
print(f"Original List: {numbers}")

Original List: [50, 40, 30, 20, 10]

In [2]:
# Append used to add an element.
numbers.append("Alpha")
print(f"After Append{numbers}")

After Append[50, 40, 30, 20, 10, 'Alpha']

In [3]:
# Extend used to add multiple elements.
numbers.extend(["Alpha","Alpha","Beta","Sigma"])
print(f"After Extend{numbers}")

After Extend[50, 40, 30, 20, 10, 'Alpha', 'Alpha', 'Alpha', 'Beta', 'Sigma']

In [4]:
# Insert used to add an element at specific position.
numbers.insert(8,"Gamma") # inserting "Gamma" at index 8
print(f"After Insert{numbers}")

After Insert[50, 40, 30, 20, 10, 'Alpha', 'Alpha', 'Alpha', 'Gamma', 'Beta', 'Sigma']

In [5]:
# Count used to count the number of occurrences of a value in a list.
numbers.count("Alpha")

3

In [6]:
# Sort used to sort elements in order.
numbers.sort(key=str) #key=str is used because my list contains strings.
print(numbers)

[10, 20, 30, 40, 50, 'Alpha', 'Alpha', 'Alpha', 'Beta', 'Gamma', 'Sigma']

In [7]:
# Reverse is used to reverse the sorted list.
numbers.reverse()
numbers

['Sigma', 'Gamma', 'Beta', 'Alpha', 'Alpha', 'Alpha', 50, 40, 30, 20, 10]

In [8]:
# Index used to find an element.
numbers.index(50)

6

In [9]:
# Remove used to remove an element.
numbers.remove("Gamma")
print(f"After Remove{numbers}")

After Remove['Sigma', 'Beta', 'Alpha', 'Alpha', 'Alpha', 50, 40, 30, 20, 10]

In [10]:
# Pop used to remove an element.
numbers.pop()     # removing last element
print(f"After Pop{numbers}")

After Pop['Sigma', 'Beta', 'Alpha', 'Alpha', 'Alpha', 50, 40, 30, 20]

In [11]:
# Claer is used to empty the list.
numbers.clear()
numbers

[]

### 2.	Creating a tuple that stores 3 student names & changing the second name in the tuple.

In [13]:
# An error is occured because tuples are immutable.
Student_Names=("John","Mary","Peter") # Creating a tuple with three elements
Student_Names[2]="James" # Changing the second element of the tuple
print(Student_Names)

TypeError: 'tuple' object does not support item assignment

### 3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [14]:
# Output Duplicates are disappear – when the set s is built, Python keeps only one copy of each value.(UNIQUE VALUES) but the ordering of those values is not guaranteed.
s = {9,9,8,8,8,7,6,5,4,3,2,1,2,3,4,5,6,7,8,19}
s

{1, 2, 3, 4, 5, 6, 7, 8, 9, 19}

### 4. Creating a dictionary with the keys: 'name', 'age', and 'city'. Updating the age and adding a new key 'email'. Printing the final dictionary.

In [15]:
# create the dictionary with three keys
details = {'name': 'Anna', 'age': 25, 'city': 'New York'}

# update the existing key 'age'
details['age'] = 26          # ← new age

# add a brand‑new key/value pair
details['email'] = 'anna123@email.com'

details

{'name': 'Anna', 'age': 26, 'city': 'New York', 'email': 'anna123@email.com'}

### 5. Writing a script that checks if a person is eligible to vote (age ≥ 18).using age as a variable and printing the appropriate message.

In [16]:
# checking the person's eligibility for voting(userinput)
age = int(input("Enter your age: "))

# ----- Condition -----
if age >= 18:
    print("You are eligible to vote.")          # age 18 or older
else:
    print("You are not eligible to vote.")      # age below 18

You are eligible to vote.

### 6.	Given a 'marks' variable, print the grade:90 and above: 'A', 75–89: 'B' , 50–74: 'C' , Below 50: 'Fail'

In [17]:
# Using marks to calulate the grade.(user_input)
marks = int(input("Enter the marks (0 ‑ 100): "))

if marks >= 90:                 # above 90
    grade = "A"
elif marks >= 75:              # 75‑89
    grade = "B"
elif marks >= 50:              # 50‑74
    grade = "C"
else:                          # anything below 50
    grade = "Fail"

print(f"Marks: {marks} → Grade: {grade}")

Marks: 88 → Grade: B

### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [18]:
num = int(input("Enter a number: "))

if num > 0:     # to get positive numbers.
                # inside a positive block we can also test for evenness
    if num % 2 == 0:
        print("Positive and even")
    else:
        print("Positive but odd")
elif num == 0:  # not positive -- is zero
    print("Zero")
else:           # negative numbers
    print("Negative")

Positive but odd

## Section B: Numpy

### 8.	Create:- A scalar using np.array(5) ,- A 1D array with values 1 to 5 , - A 2D array (2x3) with values from 10 to 60 in steps of 10

In [19]:
import numpy as np # importing numpy library
# Scalar (0‑D array)
scalar = np.array(5)  # a single value inside a NumPy array
print("scalar :", scalar, " shape:", scalar.shape)

scalar : 5  shape: ()

In [20]:
# 1‑D array with values 1-5 
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D_array :", arr_1d, " shape:",arr_1d.shape)

1D_array : [1 2 3 4 5]  shape: (5,)

In [21]:
# 2-D array with values from 10 to 60 in step of 10.
arr_2d = np.arange(10, 61, 10).reshape(2,3)
print("2D_array :", arr_2d," shape:",arr_2d.shape)

2D_array : [[10 20 30]
 [40 50 60]]  shape: (2, 3)

### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [22]:
import numpy as np 

rand_num = np.random.randint(0,101,size=(4,4)) # generating the random numbers in range (0,101)
print(rand_num)

[[76  0 98 86]
 [21 33 97 47]
 [ 9 23 15 77]
 [27 47 75 57]]

### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [23]:
import numpy as np
import pandas as pd

# 3 × 3 NumPy array (here we just use 90‑99 for clarity)
a = np.arange(90,99).reshape(3, 3)      # shape = (3, 3)

# Converting into pandas DataFrame and adding the columns names as: A, B, C
df = pd.DataFrame(a, columns=['A', 'B', 'C'])
print(df)

    A   B   C
0  90  91  92
1  93  94  95
2  96  97  98

## Section C: Exploring Pandas

### 11.	Create a small DataFrame manually with 10 rows and columns:
- 'Name', 'Age', 'City', and 'Salary'.
- Then:- Use .info(), .describe() 
- Select 'Name' and 'City' columns ,
- Drop 'City' column ,
- Fill any missing values in 'Salary' column with the mean , 
- Remove any duplicate rows.

In [24]:
import numpy as np
import pandas as pd
# Creating a DataFrame with the given instruction.
df = pd.DataFrame({
    "Name"  : ["Alice","Bob","Carol","David","Eva","Frank","Grace","Hank","Ivy","Alice"],
    "Age"   : [23,34,29,42,31,27,38,45,26,23],
    "City"  : ["NY","Paris","Tokyo","Berlin","Sydney","London","Toronto","Dubai","Mumbai","NY"],
    "Salary": [56000, np.nan, 72000, 88000, 64000,48000, 73000, np.nan, 69000, 56000]})
df

    Name  Age     City   Salary
0  Alice   23       NY  56000.0
1    Bob   34    Paris      NaN
2  Carol   29    Tokyo  72000.0
3  David   42   Berlin  88000.0
4    Eva   31   Sydney  64000.0
5  Frank   27   London  48000.0
6  Grace   38  Toronto  73000.0
7   Hank   45    Dubai      NaN
8    Ivy   26   Mumbai  69000.0
9  Alice   23       NY  56000.0

In [25]:
df.info() # Checking the information of DataFrame.

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     str
 1   Age     10 non-null     int64
 2   City    10 non-null     str
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), str(2)
memory usage: 452.0 bytes

In [26]:
df.describe() # Checking the description of DataFrame.

             Age        Salary
count  10.000000      8.000000
mean   31.800000  65750.000000
std     7.757434  12566.963493
min    23.000000  48000.000000
25%    26.250000  56000.000000
50%    30.000000  66500.000000
75%    37.000000  72250.000000
max    45.000000  88000.000000

In [27]:
df[["Name","City"]] # to get the columns "Name" and "City".

    Name     City
0  Alice       NY
1    Bob    Paris
2  Carol    Tokyo
3  David   Berlin
4    Eva   Sydney
5  Frank   London
6  Grace  Toronto
7   Hank    Dubai
8    Ivy   Mumbai
9  Alice       NY

In [28]:
df =df.drop(columns=["City"]) # To remove the column "City".
df

    Name  Age   Salary
0  Alice   23  56000.0
1    Bob   34      NaN
2  Carol   29  72000.0
3  David   42  88000.0
4    Eva   31  64000.0
5  Frank   27  48000.0
6  Grace   38  73000.0
7   Hank   45      NaN
8    Ivy   26  69000.0
9  Alice   23  56000.0

In [29]:
mean_salary = df["Salary"].mean() # Calculating the mean of Salary for missing values.
df["Salary"] = df["Salary"].fillna(mean_salary)
df

    Name  Age   Salary
0  Alice   23  56000.0
1    Bob   34  65750.0
2  Carol   29  72000.0
3  David   42  88000.0
4    Eva   31  64000.0
5  Frank   27  48000.0
6  Grace   38  73000.0
7   Hank   45  65750.0
8    Ivy   26  69000.0
9  Alice   23  56000.0

In [30]:
df = df.drop_duplicates().reset_index(drop=True) # Removing duplicate rows and resetting index.
df

    Name  Age   Salary
0  Alice   23  56000.0
1    Bob   34  65750.0
2  Carol   29  72000.0
3  David   42  88000.0
4    Eva   31  64000.0
5  Frank   27  48000.0
6  Grace   38  73000.0
7   Hank   45  65750.0
8    Ivy   26  69000.0